/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Camaro2.glb 
*/

import React, { useRef } from 'react'
import { useSnapshot } from "valtio"

import { useGLTF } from '@react-three/drei'
import { useCustomization } from '../context/Customization';
import { state } from '../components/ColorPicker';


export function Camaro(props) {
  const { nodes, materials } = useGLTF('models/Camaro.glb')
  const { overlay } = useCustomization()
  const snap1 = useSnapshot(state)

  const canvasRef = useRef(document.createElement("canvas"));
  const textureRef = useRef();
  const context = useRef(canvasRef.current.getContext("2d"));
console.log()

  canvasRef.current.width = 1600;
  canvasRef.current.height = 1600;

  let ctx = context.current;

  ctx.globalCompositeOperation = "hue";

  const img = document.getElementById(`overlay${overlay}`);

  if (img.complete) {
    ctx.drawImage(img, 0, 0);
    if (snap1.base.BaseMtl !== "none") {
      if(overlay!==1){
      ctx.fillStyle = snap1.base.BaseMtl;
      ctx.fillRect(0, 0, 1600, 1600);
      }
    }


    if (textureRef.current) {
      textureRef.current.needsUpdate = true;
    }
  }

  else {
    img.onload = function () {
      ctx.drawImage(img, 0, 0);
      if (snap1.base.BaseMtl !== "none") {
        if(overlay!==1){
        ctx.fillStyle = snap1.base.BaseMtl;
        ctx.fillRect(0, 0, 1600, 1600);
        }
      }
      


      if (textureRef.current) {
        textureRef.current.needsUpdate = true;
      }
    }
  }



  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body.geometry} rotation={[Math.PI / 2, 0, 0]} scale={0.017}>
        <meshStandardMaterial {...materials.BaseMtl} color={overlay==1 || overlay==13 ? (snap1.base.BaseMtl!=="none" ? snap1.base.BaseMtl : 0xffffff) : 0xffffff}>
          <canvasTexture
            flipY={false}
            wrapS={1000}
            wrapT={1000}
            colorSpace='srgb'
            ref={textureRef}
            attach="map"
            image={canvasRef.current}
          />
        </meshStandardMaterial>
      </mesh>
      <mesh geometry={nodes.BrakeCaliper001.geometry} material={materials.wire_010010010} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.BrakeCaliper002.geometry} material={materials.wire_010010010} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.BrakeCaliper003.geometry} material={materials.wire_010010010} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.BrakeCaliper004.geometry} material={materials.wire_010010010} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.BrakeDisk001.geometry} material={materials.BrakeDisk} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.BrakeDisk002.geometry} material={materials.BrakeDisk} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.BrakeDisk003.geometry} material={materials.BrakeDisk} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.BrakeDisk004.geometry} material={materials.BrakeDisk} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.BumperLight.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Camaro_Badge.geometry} material={materials.Matte_Chrome} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Consol.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Console_Screen.geometry} material={materials.Interior_Screens} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Dashboard.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.FogLight.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Front_ZL1_Badge.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.FrontChevyBadge.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Gauges_Frame.geometry} material={materials.BlackPlastic} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Gauges_Glass.geometry} material={materials.ClearGlass} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Gauges_Screen.geometry} material={materials.Interior_Screens} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Grille.geometry} material={materials.GlossyBlackPlastic} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Headlight.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Headlight_Glass.geometry} material={materials.ClearGlass} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Headlight_ReflectorGlass.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Hood_Insert.geometry} material={materials.GlossyBlackPlastic} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Hood_ZL1_Badge001.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Hood_ZL1_Badge002.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Interior_Body.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.InteriorMirror.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Needle001.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Needle002.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Pedals.geometry} material={materials.BlackPlastic} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Rear_ZL1_Badge.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.RearChevyBadge.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Rim001.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Rim002.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Rim003.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Rim004.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Seats.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Sidelights.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.SteerWheel.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Stoplight.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.TailLight.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.TailLight_Glass.geometry} material={materials.Taillight_Glass} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Tire001.geometry} material={materials.Tire} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Tire002.geometry} material={materials.tires} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Tire003.geometry} material={materials.Tire} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Tire004.geometry} material={materials.Tire} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Underbody.geometry} material={materials.Underbody} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.WindowGlass.geometry} material={materials.WindowGlass} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.WiperArm_001.geometry} material={materials.BlackPlastic} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.WiperArm_002.geometry} material={materials.BlackPlastic} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.WiperBlade_001.geometry} material={materials.BlackPlastic} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.WiperBlade_002.geometry} material={materials.BlackPlastic} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.MirrorR.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.MirrorL.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Spoiler.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.HandleL.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.HandleR.geometry} material={materials.wire_002002002} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Body020.geometry} material={materials.mirror} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Body021.geometry} material={materials.mirror} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
    </group>
  )
}

useGLTF.preload('/Camaro.glb')
